name: ambient_tweedie
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.5.1=cuda126*
  - torchvision
  - transformers
  - datasets
  - imageio
  - seaborn
  - plotly
  - wandb
  - s3fs
  - accelerate
  - safetensors
  - peft
  - webdataset
  - diffusers
  - pip:
    - invisible_watermark
    - opencv-python
    - imagecorruptions
    - git+https://github.com/giannisdaras/ambient_utils.git
