expr_id: train_high_level_ffhq

# general params
pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
pretrained_vae_model_name_or_path: madebyollin/sdxl-vae-fp16-fix
caption_column: text   
resolution: 1024 
random_flip: True   
checkpointing_steps: 500   

# dataset size (use this option to limit dataset size)
# max_train_samples: 3000

# optimization params
learning_rate: 1e-05
lr_scheduler: constant 
lr_warmup_steps: 0   
mixed_precision: fp16
validation_prompt: "A close-up of a person"
seed: 42   

# Dataset params
train_data_dir: "$FFHQ_RAW_DATA"
train_batch_size: 1
num_train_epochs: 50
gradient_accumulation_steps: 16

# logging
min_validation_steps: 100
validation_steps: 1000
skip_first_epoch: False
report_to: wandb
output_dir: "$BASE_PATH/ffhq_high_level/"  

# ambient params
noisy_ambient: True
timestep_nature: 500
x0_pred: True

# consistency params
consistency_kick_in: 50000  # after how many steps should consistency kick in
consistency_coeff: 0.01
num_consistency_steps: 1
max_steps_diff: 100
run_consistency_everywhere: True
with_grad: False            # NZ: was missing in the original file
                            # Set to False to save memory

# FID params
track_fid: True
fid_ref_path: "$FFHQ_REF_PATH"
num_images_for_fid: 1024

# resume training
resume_from_checkpoint: "latest"

